files:
  image: debian
  volumes:
    - .:/www
www:
  build: .
  volumes_from:
  - files
  ports:
    - 8080:8080
nginx:
  build: .
  dockerfile: 'Dockerfile.nginx-www'
  volumes_from:
  - files
  ports:
  - 8888:80
